### ISSUE TITLE
Pair Wines to each Set Menu

### ISSUE THREAD

**Issue by sarahannecorder** [studentsofdesign/group-recipes#139]
@GabrielHair @brvhart @MrFinn Hi Guys, we need to please pair up each Menu with a selection of wines. You can find these Set Menus under the projects panel under 'Set Menu's Per Day'
Just edit each one - i.e copy and paste under each dish. Thanks!

**Comment by brvhart** [comment]
@GabrielHair @MrFinn guys I'll tackle the set menu pairings from 6-10  - chad

**Comment by GabrielHair** [comment]
Done.
