### ISSUE TITLE
Combine issues #124 , #125 and #126 and format

### ISSUE THREAD

**Issue by Guibertos** [studentsofdesign/group-recipes#143]
- [x] open up a new project called Day 1
- [x] combine ingredients for set menu #124 , #125  & #126  in shopping list
- [x] Heading for shopping list H1 & Bold and written in sentence case
- [x] Ingredients listed in unordered list
- [x] Dbl check that it is in metrics system 
- [x] Convert Tablespoons, teaspoons and cup into equivalent grams and ml

**Comment by sarahannecorder** [comment]
Completed issue
