### ISSUE TITLE
Combine issues #127 #128 & #129# and format

### ISSUE THREAD

**Issue by Guibertos** [studentsofdesign/group-recipes#144]
- [x] open new project called Day 2
- [x] combine ingredients for set menu #127 #128 & #129 in shopping list
- [x] Heading for shopping list H1 & Bold and written in sentence case
- [x] Ingredients listed in unordered list
- [x] Dbl check that it is in metrics system 
- [x] Convert Tablespoons, teaspoons and cup into equivalent grams and ml

**Comment by christieeveleigh0** [comment]
# Shopping Lists For Set Menu #127 , #128 and #129 

- 1 lemon
- 454 grams red and green grapes
- 768 grams cups black cherries, pitted or unpitted
- 2 red onions
- 3 yellow onion
- 12 pearl onions
- 250g White Button mushrooms
- 2 carrots
- 500 grams fresh asparagus spears, trimmed, cut into 1-inch pieces
- 118,294ml chopped drained roasted red bell peppers 
- 5 garlic cloves
- 1 spring fresh rosemary
- 13.5 grams of thyme
- 2 bay leaf
- 2 sprigs fresh parsley, chopped
- 248ml white wine
- 125ml red wine
- 1 loaf fresh baked Mediterranean bread (shop bought
- 115 grams gluten-free pasta
- 1 refrigerated pie crust
- 155 grams of butter
- 30ml olive oil
- 30 ml balsamic vinegar
- 30 grams tomato paste
- 250ml vegetable broth
- 472ml chicken broth
- Salt and freshly ground pepper
- 500 grams of choux pastry (shop bought)
- 450 grams pastry cream (crème patissière), at room temperature
- 20g unsweetened chocolate
- 30 grams strong cocoa powder
- 200 grams white fondant icing
- Confectioners' sugar
- 384 grams flour
- 22.5 grams gluten-free flour
- 176.4 grams sugar
- 29 grams vanilla extract 
- 29 grams double cream
- 354 ml milk
- 59 grams kirsch
- 500 grams mussels
- 500 grams clams
- 908 grams boneless rib-end pork loin roast
- 4 thin slices prosciutto, chopped
- 17 eggs
- 1 box camembert
- 1 log chèvre (goat) cheese, crumbled
- 118,294ml freshly shredded Parmesan cheese

1 Bottle Sauternes
1 Bottle Chenin Blanc
1 Bottle Pinot Noir
1 Bottle Cabernet Sauvignon
1 Bottle Chardonnay
1 Bottle Sparkling Wine
1 Bottle Sauvignon Blanc
1 Bottle Pink Champagne
