### ISSUE TITLE
Double Check the Roster

### ISSUE THREAD

**Issue by ARTHURLIMBADA** [studentsofdesign/group-recipes#166]
Check if the amount of people working on a recipe is the correct amount.

**Comment by SirMrDrewZA** [comment]
**DAY 1**

**SET MENU 3**

We need to change the Set Menu - Pastry is to long

**SET MENU 2**

Changed Pastry from 2 to 1 

**SET MENU 3**

Has been double checked and is all correct

**Comment by ARTHURLIMBADA** [comment]
DAY 5

SET MENU 12
We have to change this set Menu.

SET MENU 11
Everything is Correct

SET MENU 10
Everything is Correct

**Comment by SirMrDrewZA** [comment]
**DAY 3**

**SET MENU 9**

Pastry changed from 2 to 1

**SET MENU 8**

Pastry changed from 2 to 1

**SET MENU 7**

Grilled changed from 2 to 1

**Comment by Yorkshiire** [comment]
## Day 2

#### Set menu 6
We have to **change** this order

#### Set menu 5
**Changed** the number of people too 1 person
Has been corrected

#### Set menu 4
**Changed** the number of people too 1 person
Has been corrected.
