### ISSUE TITLE
Set menus that need to be changed.

### ISSUE THREAD

**Issue by ARTHURLIMBADA** [studentsofdesign/group-recipes#172]
List all the set menus that need to be changed.

**Comment by mylesarendse** [comment]
@sarahannecorder Guys, do you already know which desserts need to be changed?

**Comment by ARTHURLIMBADA** [comment]
@mylesarendse Apple Tart and Cherry Clafoutis

**Comment by Yorkshiire** [comment]
## Day 2

### Set menu 6

Cherry Clafoutis (Sauternes)
Bake:90mins
Already bake 60min

**Comment by ARTHURLIMBADA** [comment]
## Day 5

### Set Menu 14

Apple Tarte (Pink Champagne) 
Pastry: 1hr40
