### ISSUE TITLE
Change set menu total time

### ISSUE THREAD

**Issue by SirMrDrewZA** [studentsofdesign/group-recipes#182]
Change set menus total times

- [x] Day 1

- [x] Day 2

- [x] Day 3

- [x] Day 4

- [x] Day 5

**Comment by SirMrDrewZA** [comment]
Day 1 and 4 checked and changed

**Comment by Yorkshiire** [comment]
Day 3 and 5 checked and changed

**Comment by Yorkshiire** [comment]
Day 4 changed
