### ISSUE TITLE
Find 10 French Mains

### ISSUE THREAD

**Issue by christieeveleigh0** [studentsofdesign/group-recipes#77]
Please find French mains & comment the links.

**Comment by SirMrDrewZA** [comment]
# French Main Ideas

https://www.bettycrocker.com/recipes/global-cuisine/french-recipes/french-main-dish

**Comment by slvrshadow** [comment]
https://www.foodandwine.com/recipes/lyon-style-chicken-with-vinegar-sauce

**Comment by brvhart** [comment]
Marseille-Style Shrimp Stew / Suggested Pairing
Crisp Provençal rosé.
https://www.foodandwine.com/recipes/marseille-style-shrimp-stew

**Comment by slvrshadow** [comment]
https://www.foodandwine.com/recipes/red-snapper-with-citrus-and-fennel-salad

**Comment by slvrshadow** [comment]
Asparagus and goat cheese quiche
https://www.bettycrocker.com/recipes/asparagus-and-goat-cheese-quiche/1d2bffea-b450-431a-9a83-d1a01c9e116c

**Comment by brvhart** [comment]
Braised Pork with Pearl Onions and Grapes/ **Suggested Pairing**
A California Pinot Noir with aromas of cherry, strawberry and toasty oak is a great match
https://www.foodandwine.com/recipes/braised-pork-with-pearl-onions-and-grapes

**Comment by slvrshadow** [comment]
Steak haché with pommes frites & cheat's Béarnaise sauce
https://www.bbcgoodfood.com/recipes/steak-hache-pommes-frites-cheats-bearnaise-sauce

**Comment by slvrshadow** [comment]
Sautéed potatoes with bacon lardons & persillade
https://www.bbcgoodfood.com/recipes/sauteed-potatoes-bacon-lardons-persillade

**Comment by slvrshadow** [comment]
French-style chicken with peas & bacon
https://www.bbcgoodfood.com/recipes/518641/frenchstyle-chicken-with-peas-and-bacon

**Comment by slvrshadow** [comment]
Summer fish stew with rouille
https://www.bbcgoodfood.com/recipes/532640/summer-fish-stew-with-rouille

**Comment by brvhart** [comment]
Katie Lee’s Sole Meunière Recipe/ **suggested paring** - A white wine, like a Sancerre.
http://www.foodrepublic.com/recipes/katie-lees-sole-meuniere-recipe/

**Comment by brvhart** [comment]
MAGRETS DE CANARD WITH PEACHES AND POTATO CAKE / **suggested pairing** -A red Bordeaux.
http://mimithorisson.com/2012/05/01/magret-de-canard-with-peaches-and-potato-cake/

**Comment by slvrshadow** [comment]
MUSHROOM BOURGUIGNON 
http://www.onegreenplanet.org/vegan-recipe/vegan-mushroom-bourguignon/

**Comment by brvhart** [comment]
Ratatouille / 
https://www.allrecipes.com/recipe/18411/ratatouille/?internalSource=staff%20pick&referringId=17138&referringContentType=recipe%20hub&clickId=cardslot%202
