### ISSUE TITLE
Find 10 French Starters

### ISSUE THREAD

**Issue by christieeveleigh0** [studentsofdesign/group-recipes#79]
Find 10 French Starter recipes & comment the links.

**Comment by Guy-Forster** [comment]
I'm on this!

**Comment by jaimecoue** [comment]
https://www.saveur.com/article/recipes/oeufs-en-cocotte-au-saumon-fume-eggs-baked-with-smoked-salmon

**Comment by Guy-Forster** [comment]
Moules à la Marinière - 25minutes

http://allrecipes.co.uk/recipe/1493/moules-marini-res.aspx

**Comment by Guy-Forster** [comment]
Cheese Souffles - 45 minutes

http://allrecipes.co.uk/recipe/23840/cheese-souffles.aspx

**Comment by Guy-Forster** [comment]
Baked Camembert with balsamic caramelised onions - 50 minutes

http://allrecipes.co.uk/recipe/12001/baked-camembert-with-balsamic-caramelised-onions.aspx

**Comment by Guy-Forster** [comment]
Mussels and Clams with Lemon - 12 minutes

http://allrecipes.co.uk/recipe/22938/mussels-and-clams-with-lemon.aspx

**Comment by Guy-Forster** [comment]
Eggs cocotte with prosciutto - 15min

http://allrecipes.co.uk/recipe/26764/eggs-cocotte-with-prosciutto.aspx

**Comment by jaimecoue** [comment]
**Zucchini-Tomato Verrines** 
Time: 45 Minutes

https://www.foodandwine.com/recipes/zucchini-tomato-verrines

**Comment by Guy-Forster** [comment]
Classic French onion soup - 1 hour

http://allrecipes.co.uk/recipe/14133/classic-french-onion-soup.aspx

**Comment by jaimecoue** [comment]
Reblochon Tarts with Bacon and Fingerling Potatoes
Time: 40 Minutes

https://www.foodandwine.com/recipes/reblochon-tarts-with-bacon-and-fingerling-potatoes

**Comment by Guy-Forster** [comment]
Scallops with parsley butter - 15 minutes

http://allrecipes.co.uk/recipe/25240/scallops-with-parsley-butter.aspx
