### ISSUE TITLE
Find A Couple Of French Wines

### ISSUE THREAD

**Issue by christieeveleigh0** [studentsofdesign/group-recipes#80]
Find French Wines & comment links.

**Comment by MrFinn** [comment]
https://www.port2port.wine/buy-wine/domaine-jacques-prieur/puligny-montrachet-les-combettes-1er-cru-2014

Chicken Lion possible pairing

**Comment by MrFinn** [comment]
https://www.port2port.wine/buy-wine/château-rieussec/sauternes-2009

for pairing with seafood

**Comment by MrFinn** [comment]
https://www.port2port.wine/buy-wine/de-ladoucette/baron-de-l-2012

possible pairing for the goat cheese quiche

**Comment by MrFinn** [comment]
https://www.port2port.wine/buy-wine/dom-pérignon/brut-millésimé-2009

possible pairing for Duck

**Comment by MrFinn** [comment]
https://www.port2port.wine/buy-wine/château-de-chamirey/mercurey-1er-cru-clos-des-ruelles-2014

possible pairing for braised pork

**Comment by MrFinn** [comment]
https://www.port2port.wine/buy-wine/château-giscours/grand-cru-classé-2012

possible pairing for steak haché

**Comment by MrFinn** [comment]
https://www.port2port.wine/buy-wine/château-pape-clément/grand-cru-classé-de-graves-2013

possible pairing for Sautéed potatoes with bacon

**Comment by MrFinn** [comment]
https://www.port2port.wine/buy-wine/domaine-jacques-prieur/puligny-montrachet-les-combettes-1er-cru-2014

possible pairing for French-style chicken with peas & bacon

**Comment by MrFinn** [comment]
https://www.port2port.wine/buy-wine/domaine-albert-morot/beaune-1er-cru-les-aigrots-2006?search_query=Burgundy

possible pairing for Mushroom Bourguignon
