### ISSUE TITLE
Find 5 French Desserts

### ISSUE THREAD

**Issue by christieeveleigh0** [studentsofdesign/group-recipes#82]
Find 5 frech Desserts & comment links.

**Comment by YazB15** [comment]
I'm on this!

**Comment by YazB15** [comment]
https://www.allrecipes.com/recipe/19165/creme-brulee/

**Comment by Yorkshiire** [comment]
https://www.allrecipes.com/recipe/19165/creme-brulee/?internalSource=staff%20pick&referringId=1828&referringContentType=recipe%20hub

**Comment by Yorkshiire** [comment]
https://www.allrecipes.com/recipe/77874/french-apple-tart-tarte-de-pommes-a-la-normande/?internalSource=staff%20pick&referringId=1828&referringContentType=recipe%20hub

**Comment by SirMrDrewZA** [comment]
# Chocolate éclairs

- Cooking time : 30mins-1hour

https://www.bbc.com/food/recipes/chocolate_clairs_03600

**Comment by SirMrDrewZA** [comment]
# Cherry Clafoutis 

- Cooking time : 45 mins 

https://www.saveur.com/article/Recipes/Cherry-Clafoutis

**Comment by SirMrDrewZA** [comment]
# Gâteau St Honoré

 - Cooking time: 1-2 hours

https://www.bbc.com/food/recipes/gteau_st_honor_85590
