### ISSUE TITLE
Create Rotations Of Menu

### ISSUE THREAD

**Issue by christieeveleigh0** [studentsofdesign/group-recipes#88]
Collect the recipes in the issue categories & create daily menu rotations AFTER the voting phase.
For example, 'Day 1 Starters'

**Comment by Guibertos** [comment]
***Set Menu 1***

1. Moules à la Marinière
2. Crunchy Almond Crusted Duck Breast
3. Cream Puffs

**Comment by Guibertos** [comment]
***Set Menu 2***

1. Cheese Souffle
2. French-style chicken with peas and bacon
3. Chocolate éclaires

**Comment by Guibertos** [comment]
***Set Menu 3***

1. Eggs Baked with Smoked Salmon
2. Steak haché with pommes frites & Béarnaise sauce

**Comment by Guibertos** [comment]
***Set Menu 4***

1. Baked camembert with balsamic caramelised onions
2. Mushroom Bourguignon
3. Chocolate éclaires

**Comment by Guibertos** [comment]
***Set Menu 5***

1. Mussels and clams with Lemon
2. Braised Pork with pearl onions and grapes
3. Cherry Clafoutis

**Comment by Guibertos** [comment]
***Set Menu 6***

1. Eggs cocotte with prosciutto
2. Asparagus and goat cheese quiche
3. Cherry Clafoutis

**Comment by Guibertos** [comment]
***Set Menu 7***

1. Zucchini and tomato Verrines
2. Red Snapper with citrus and fennel salad
3. Gâteau St Honoré

**Comment by Guibertos** [comment]
***Set Menu 8***

1. Onion Soup
2. Sauteed Potatoes with bacon & persillade
3. Gâteau St Honoré

**Comment by Guibertos** [comment]
***Set Menu 8***

1. Reblochon Tarts with bacon and fingerling potatoes
2. Marseille style shrimp stew
3. Chocolate éclaires

**Comment by Guibertos** [comment]
***Set Menu 11***

1. Moules à la Marinière
2. French-style chicken with peas and bacon
3. Apple Tarte

**Comment by Guibertos** [comment]
***Set Menu 12***

1. Onion Soup
2. Mushroom Bourguignon
3. Cherry Clafoutis

**Comment by Guibertos** [comment]
***Set Menu 13***

1. Reblochon Tarts with bacon and fingerling potatoes
2. Steak haché with pommes frites & Béarnaise sauce
3. Gâteau St Honoré

**Comment by Guibertos** [comment]
***Set Menu 14***

1. Scallops with Parsley Butter
2. Crunchy Almond Crusted Duck Breast
3. Apple Tarte
